### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by peterpants2** [ash4rk/guake#1]
What will the license be for this project? I really like the character model is that something you made?

**Comment by ash4rk** [comment]
Hi, en4ian!

Character model not mine, but it CC0 licensed.
There is a [link](https://stephrobertgames.itch.io/anime-character-low-poly-psx) to source.
I found it in [this](https://github.com/Miziziziz/Retro3DGraphicsCollection) repo by Miziziziz. Check out there are a lot of cool low poly ps1 stylized models.

I added [CREDITS.md](https://github.com/ash4rk/guake/blob/main/CREDITS.md). So you can find references to the assets i use.

**Comment by ash4rk** [comment]
Added MIT [LICENSE](https://github.com/ash4rk/guake/blob/main/LICENSE) to project, but so far it only covers the code I wrote. The rest of the assets need to be specified, but I'll do my best to have them under MIT or CC.

**Comment by peterpants2** [comment]
Nice! Thank you
